#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Aug 01 21:24:46 KST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=TrailerShaders_v1.4.zip
